"""Added `trusted` column to UserModel

Revision ID: 0b139eaaf452
Revises: a2fb23917cf8
Create Date: 2021-04-24 19:43:30.967366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b139eaaf452'
down_revision = 'a2fb23917cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trusted', sa.Boolean(), server_default=sa.text('1'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('trusted')

    # ### end Alembic commands ###
